[package]
name = "Proyecto1"
version = "0.1.0"
authors = ["Pedro <pdiaz@grupogrameco.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
